version: "2.4"
services:
  wireguard-socks5:
    image: jouyouyun/wireguard-socks5:latest
    volumes:
      - ./config:/etc/wireguard/
      - /lib/modules:/lib/modules
      - /dev/net/tun:/dev/net/tun
    ports:
      - 1080:1080
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
